[package]
name = "libXNVCtrl-sys"
version = "1.29.1"
authors = ["zee-mzha <zee.mzha@gmail.com>"]
edition = "2018"
description = "Rust bindings for Nvidia's XNVCtrl library"
license-file = "LICENSE.md"

[dependencies]
x11 = "2.18.2"

[build-dependencies]
bindgen = "0.53.2"
