[package]
name = "libXNVCtrl-sys"
version = "0.1.0"
authors = ["zee-mzha <zee.mzha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
x11 = "2.18.2"

[build-dependencies]
bindgen = "0.53.2"
